### ISSUE TITLE
Penilaian Progress-1 Projek STA1562 MDS

### ISSUE THREAD

**Issue by alfanugraha** [MDS6/MDS6#1]
## **NILAI PROGRESS-1: 97**  

NICE! @setyo83 @diaztrihazam @fulazz @Intanjulianapanjaitan 

Beberapa catatan yang harus diperhatikan:
- Mohon ditambahkan **ulasan** yang lebih komprehensif tentang database yang ingin dikembangkan
- Cantumkan (unggah jika sudah ada) rencana data yang akan diperoleh dan digunakan pada projek ini
- Lampirkan **skema diagram**

**Comment by fulazz** [comment]
Mas Alfa, untuk skema diagram sudah dilampirkan mas setyo di bagian paling bawah...

**Comment by alfanugraha** [comment]
> Mas Alfa, untuk skema diagram sudah dilampirkan mas setyo di bagian paling bawah...

Skema dan ER diagram beda yaa @fulazz

**Comment by fulazz** [comment]
Oh iya beda, baik mas Alfa.. terimakasih

> > Mas Alfa, untuk skema diagram sudah dilampirkan mas setyo di bagian paling bawah...
> 
> Skema dan ER diagram beda yaa @fulazz

**Comment by setyo83** [comment]
> ## **NILAI PROGRESS-1: 87**
> NICE! @setyo83 @diaztrihazam @fulazz @Intanjulianapanjaitan
> 
> Beberapa catatan yang harus diperhatikan:
> 
> * Mohon ditambahkan **ulasan** yang lebih komprehensif tentang database yang ingin dikembangkan
> * Cantumkan (unggah jika sudah ada) rencana data yang akan diperoleh dan digunakan pada projek ini
> * Lampirkan **skema diagram**

Terima kasih atas catatannya, sudah kami update ya mas, untuk data dummy sudah kami attach juga sesuai dengan nama tabel masing-masing
